export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL';

export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL';
export const CATEGORY_CREATE_RESET = 'CATEGORY_CREATE_RESET';

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL';
export const CATEGORY_UPDATE_RESET = 'CATEGORY_UPDATE_RESET';

export const PLANT_LIST_REQUEST = 'PLANT_LIST_REQUEST';
export const PLANT_LIST_SUCCESS = 'PLANT_LIST_SUCCESS';
export const PLANT_LIST_FAIL = 'PLANT_LIST_FAIL';

export const PLANT_DELETE_REQUEST = 'PLANT_DELETE_REQUEST';
export const PLANT_DELETE_SUCCESS = 'PLANT_DELETE_SUCCESS';
export const PLANT_DELETE_FAIL = 'PLANT_DELETE_FAIL';

export const PLANT_CREATE_REQUEST = 'PLANT_CREATE_REQUEST';
export const PLANT_CREATE_SUCCESS = 'PLANT_CREATE_SUCCESS';
export const PLANT_CREATE_FAIL = 'PLANT_CREATE_FAIL';
export const PLANT_CREATE_RESET = 'PLANT_CREATE_RESET';

export const PLANT_UPDATE_REQUEST = 'PLANT_UPDATE_REQUEST';
export const PLANT_UPDATE_SUCCESS = 'PLANT_UPDATE_SUCCESS';
export const PLANT_UPDATE_FAIL = 'PLANT_UPDATE_FAIL';
export const PLANT_UPDATE_RESET = 'PLANT_UPDATE_RESET';

export const SUBCATEGORY_LIST_REQUEST = 'SUBCATEGORY_LIST_REQUEST';
export const SUBCATEGORY_LIST_SUCCESS = 'SUBCATEGORY_LIST_SUCCESS';
export const SUBCATEGORY_LIST_FAIL = 'SUBCATEGORY_LIST_FAIL';

export const SUBCATEGORY_DELETE_REQUEST = 'SUBCATEGORY_DELETE_REQUEST';
export const SUBCATEGORY_DELETE_SUCCESS = 'SUBCATEGORY_DELETE_SUCCESS';
export const SUBCATEGORY_DELETE_FAIL = 'SUBCATEGORY_DELETE_FAIL';

export const SUBCATEGORY_CREATE_REQUEST = 'SUBCATEGORY_CREATE_REQUEST';
export const SUBCATEGORY_CREATE_SUCCESS = 'SUBCATEGORY_CREATE_SUCCESS';
export const SUBCATEGORY_CREATE_FAIL = 'SUBCATEGORY_CREATE_FAIL';
export const SUBCATEGORY_CREATE_RESET = 'SUBCATEGORY_CREATE_RESET';

export const SUBCATEGORY_UPDATE_REQUEST = 'SUBCATEGORY_UPDATE_REQUEST';
export const SUBCATEGORY_UPDATE_SUCCESS = 'SUBCATEGORY_UPDATE_SUCCESS';
export const SUBCATEGORY_UPDATE_FAIL = 'SUBCATEGORY_UPDATE_FAIL';
export const SUBCATEGORY_UPDATE_RESET = 'SUBCATEGORY_UPDATE_RESET';